const express = require("express");
const multer = require("multer");
const { extractTextFromFile } = require("../services/fileProcessor");
const fs = require("fs");
const router = express.Router();

// Configure multer for file uploads
const upload = multer({ dest: "uploads/" });

router.post("/upload", upload.single("resume"), async (req, res) => {
  // Validate if a file is uploaded
  if (!req.file) {
    return res.status(400).json({ error: "No file uploaded" });
  }

  const filePath = req.file.path; // Temporary file path created by multer
  const originalName = req.file.originalname; // Original file name with extension

  console.log("Uploaded file path:", filePath);
  console.log("Original file name:", originalName);

  try {
    // Extract text from the uploaded file
    const fileText = await extractTextFromFile(filePath, originalName);

    // Respond with extracted text and file ID
    res.json({
      message: "File uploaded successfully",
      fileId: req.file.filename, // Unique filename generated by multer
      fileText, // Extracted text
    });
  } catch (error) {
    // Handle errors during text extraction
    console.error("Error processing file:", error.message);

    
    // console.log("Extracted Text from File:", fileText);


    // Delete the uploaded file to save space
    if (fs.existsSync(filePath)) {
      fs.unlinkSync(filePath);
      console.log(`Deleted file: ${filePath}`);
    }

    res.status(500).json({ error: "Failed to process the uploaded file" });
  }
});

module.exports = router;
